# Generated by Django 3.0.7 on 2020-12-22 13:24

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detectiondetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateTimeField(auto_now_add=True)),
                ('imageName', models.CharField(max_length=255)),
                ('detectStatus', models.CharField(max_length=255, null=True)),
                ('videoId', models.IntegerField()),
                ('imlat', models.FloatField()),
                ('imlong', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='photoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', jsonfield.fields.JSONField(null=True)),
                ('image_type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='projectdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.IntegerField()),
                ('videoName', models.CharField(max_length=80)),
                ('gpxFile', models.CharField(max_length=255)),
                ('status', models.IntegerField(null=True)),
                ('totalFrames', models.IntegerField(null=True)),
                ('detectedFrames', models.IntegerField(null=True)),
                ('dates', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='projectname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateTimeField(auto_now_add=True)),
                ('projectName', models.CharField(max_length=255)),
                ('projectDesc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='registerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80, null=True)),
                ('password', models.CharField(max_length=80)),
                ('reset_pwd_code', models.CharField(max_length=50, null=True)),
                ('reference_token', models.CharField(max_length=255, null=True)),
                ('access_token', models.CharField(max_length=255, null=True)),
                ('registered_date', models.DateField(null=True)),
                ('onlineStatus', models.CharField(default='offline', max_length=30, null=True)),
                ('mobileNumber', models.CharField(max_length=30, null=True)),
                ('approval_status', models.CharField(default='pending', max_length=30, null=True)),
                ('mobileCountryCode', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
