# Generated by Django 3.0.7 on 2020-10-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80, null=True)),
                ('password', models.CharField(max_length=80)),
                ('reset_pwd_code', models.CharField(max_length=50, null=True)),
                ('reference_token', models.CharField(max_length=255, null=True)),
                ('access_token', models.CharField(max_length=255, null=True)),
                ('registered_date', models.DateField(null=True)),
                ('onlineStatus', models.CharField(default='offline', max_length=30, null=True)),
                ('mobileNumber', models.CharField(max_length=30, null=True)),
                ('approval_status', models.CharField(default='pending', max_length=30, null=True)),
                ('mobileVerifiedStatus', models.IntegerField(null=True)),
            ],
        ),
    ]
