# Generated by Django 3.0.7 on 2020-11-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_projectname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetails',
            old_name='projectName',
            new_name='projectId',
        ),
    ]
