# Generated by Django 3.0.7 on 2020-11-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201111_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='projectId',
            field=models.IntegerField(max_length=20),
        ),
    ]
