# Generated by Django 3.0.7 on 2020-11-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201111_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectname',
            name='projectDesc',
            field=models.TextField(null=True),
        ),
    ]
