# Generated by Django 3.0.7 on 2020-11-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_projectname_projectdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='projectId',
            field=models.IntegerField(),
        ),
    ]
