# Generated by Django 3.0.7 on 2020-11-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201111_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='detectiondetrails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateTimeField(auto_now_add=True)),
                ('imageName', models.CharField(max_length=255)),
                ('detectStatus', models.CharField(max_length=255, null=True)),
                ('videoId', models.IntegerField()),
            ],
        ),
    ]
