# Generated by Django 3.0.7 on 2020-11-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_detectiondetrails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detectiondetrails',
            new_name='detectiondetails',
        ),
    ]
