# Generated by Django 3.0.7 on 2020-11-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201112_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
