# Generated by Django 3.0.7 on 2020-11-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_projectdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='detectedFrames',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='totalFrames',
            field=models.IntegerField(null=True),
        ),
    ]
